spring.application.name=prototype
spring.datasource.url=jdbc:postgresql://localhost:5432/curry_matching_db
spring.datasource.username=postgres
spring.datasource.password=aaaa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true