DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS users_profile CASCADE;
DROP TABLE IF EXISTS diagnosis_results CASCADE;
DROP TABLE IF EXISTS questionnaire CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role_name VARCHAR(255) NOT NULL DEFAULT 'USER',
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    password_reset_token VARCHAR(255) DEFAULT NULL,
    reset_token_expiry TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS users_profile (
    user_id BIGINT NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(500) DEFAULT NULL,
    bio VARCHAR(500) DEFAULT NULL,
    curry_mbti_type VARCHAR(10) DEFAULT NULL,
    curry_mbti_subtype VARCHAR(10) DEFAULT NULL,
    /***
     * TODO:
     * カレー屋情報実装後、
     * 好きなカレー屋のランキングデータ
     */
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS diagnosis_results(
    diagnosis_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    mbti_type VARCHAR(10) NOT NULL,
    mbti_subtype VARCHAR(10) NOT NULL,
    axis1_score INT NOT NULL,
    axis2_score INT NOT NULL,
    axis3_score INT NOT NULL,
    axis4_score INT NOT NULL,
    axis5_score INT NOT NULL,
    gender VARCHAR(10) DEFAULT NULL,
    age VARCHAR(10) DEFAULT NULL,
    diagnosed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (diagnosis_id)
);

CREATE TABLE IF NOT EXISTS questionnaire(
    questionnaire_id INT NOT NULL,
    questionnaire_type INT NOT NULL,
    question VARCHAR (255) NOT NULL,
    reversed_score BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (questionnaire_id)
);

ALTER TABLE diagnosis_results ALTER COLUMN user_id DROP NOT NULL;
